language: node_js
node_js:
  - 4.2.4
  - 5.4.0
  - 6.8.0
addons:
  firefox: "latest"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install npm -g
  - npm install jshint -g
  - npm install
  - gulp init
script:
  - gulp build
  - gulp lint
  - gulp test
  - npm test
  - codeclimate-test-reporter < coverage/lcov.info
